### PR TITLE
ca-certificates: update

### PR DESCRIPTION
**Pull request by rtollert**
Signed-off-by: Richard Tollerton <rich.tollerton@ni.com>

### CODE REVIEW

**Comment by amstewart** [comment]
What is the purpose of upgrading ca-certificates?

Is this something that we need to pull into the dunfell branch or upstream?

**Comment by rtollert** [comment]
ca-certificates is sufficiently out of date that certificates in the wild are starting to not validate.

Upstream is only slightly different — let me re-post with a cherry-pick.

**Comment by rtollert** [comment]
ok try that

**Comment by amstewart** [comment]
Much better; thanks.

**Review by amstewart — APPROVED** [review]

**Pull request merged**
