### PR TITLE
package_manager: Don't pipe stderr to stdout when writing stdout to s…

### PR DESCRIPTION
**Pull request by shruthi-ravi**
…tatus file

The status file can contain clobbered text like:
`Package: gnupg-lic 
Version: 2.2.4-r0.4 * rm_r: Failed to open dir /home/rfmibuild/myagent/_work/_r/0/src/rtos/rtoslegacyd/NIOpenEmbedded/objects/build.xilinx-zynq/tmp-glibc/work/xilinx-zynq-nilrt-linux-gnueabi/niconsole-dkms-image/1.0-r0/temp/ipktemp//opkg-2yg8jO: No such file or directory. 
Status: deinstall hold not-installed`

### Testing

I can reproduce the problem consistently on an rfmibuild test server without the related opkg [patch](https://github.com/ni/meta-nilrt/commit/c80c21a41959b55c3be44043b2601588e6270e86). After the oe-core fix, I can no longer reproduce the issue.

### Notes

This would be the longer term fix for related azdo bug [1995116](https://ni.visualstudio.com/DevCentral/_workitems/edit/1995116).
Only the -lic packages were affected because it looks like OE calls `handle_bad_recommendations()` on all the -lic packages before installing anything else in the rootfs. Therefore, the status file is first created by this function with the clobbered version.

### CODE REVIEW

**Review by amstewart — APPROVED** [review]
:partying_face: NIce! You found it.

Seems like this same bug might be [present in hardknott](https://github.com/ni/openembedded-core/blob/nilrt/master/hardknott/meta/lib/oe/package_manager/ipk/__init__.py#L112). Do you think we can upstream a fix here?

**Review by amstewart — CHANGES_REQUESTED** [review]
Could you add the detail from the PR summary to the commit message. Future log readers would like more detail about what specifically messes up in the status file.

**Comment by shruthi-ravi** [comment]
> Do you think we can upstream a fix here?

Yeah, although I don't have a reproducing test case for it. Looks like they fixed one instance of it [here](https://github.com/ni/openembedded-core/blob/c827a25b45db6e8103e42991767a5030cc8a7daf/meta/lib/oe/package_manager/ipk/__init__.py#L80), but not in other places.

**Comment by shruthi-ravi** [comment]
### Update v2:

Added error text to the commit description.

@amstewart are you good with the commit message?

**Review by amstewart — APPROVED** [review]
Yep. Looks fine.

**Pull request merged**
