### PR TITLE
opkg-utils: upgrade from 0.4.2 to 0.4.3

### PR DESCRIPTION
**Pull request by dmondrik**
Made the same changes to SRC_URI [as done in the dunfell branch](https://github.com/ni/openembedded-core/commit/810826b644f93ad3923647e387ce849c3e71bb1b#diff-6d878eba913c44ffbdf44dca0b3e6a0cbd5e5d5badd72e86e2f5ae105b81b31a).

### CODE REVIEW

**Review by amstewart — CHANGES_REQUESTED** [review]
Patch looks good.

Could you prepend the recipe name to the commit summary. Eg. `opkg-utils: upgrade from 0.4.2 to 0.4.3`

**Comment by dmondrik** [comment]
Alex I used `git commit --amend` to give it the name you suggested. 08462f5a9a8c0c70948683cbdf96519acf30b548

**Comment by dmondrik** [comment]
FYI @ni/rtos

**Comment by amstewart** [comment]
Thanks. I'm not sure what GH is doing to the object history though. Could you squash-rebase the three commits in this PR branch into a single commit with the correct summary. We try to keep the OE layers as rebase-friendly as we can, which means avoiding things like merge-commits.

**Comment by amstewart** [comment]
Once you've squashed it locally, you can just force-push to the same ref as the PR and the PR should update automatically.

**Comment by dmondrik** [comment]
I will just re-create this and try again...

**Pull request closed without merging**
