### PR TITLE
openembedded-core: Currency merge with upstream kirkstone branch

### PR DESCRIPTION
**Pull request by xhuff**
This is the 2023Q3.1 currency merge with upstream kirkstone branch
There were no merge conflicts and no additional NI-specific patches are required.

[AB#2395756](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2395756)

**Testing**
- [x] `bitbake packagefeed-ni-core`
- [x] `bitbake packagegroup-ni-desirable`

@ni/rtos

### CODE REVIEW

**Comment by chaitu236** [comment]
> Fixed 3 small conflicts

Can you mention which of the existing commits they conflicted with?

**Comment by xhuff** [comment]
> > Fixed 3 small conflicts
> 
> Can you mention which of the existing commits they conflicted with?

Crap, I put this note on the wrong PR. It should have been in https://github.com/ni/meta-openembedded/pull/38

I'll fix that

**Comment by gratian** [comment]
The merge looks fine but I think it was done before the PRs for pango (https://github.com/ni/openembedded-core/pull/102) and ncurses (https://github.com/ni/openembedded-core/pull/103) upgrades were merged. This will create an additional merge commit when this PR is merged since fast-forward merging is not possible:
```
$ git merge --ff-only xhuff/dev/automerge/ni 
fatal: Not possible to fast-forward, aborting.
```
If it's not too much trouble can you redo the merge on top of the latest `nilrt/master/kirkstone`? Since there were no conflicts it should be quick and it will make the commit history cleaner.

**Comment by xhuff** [comment]
> If it's not too much trouble can you redo the merge on top of the latest `nilrt/master/kirkstone`? Since there were no conflicts it should be quick and it will make the commit history cleaner.

Definitely, can do! Think it'll be important to redo the testing, too? I'll queue it up either way

**Review by gratian — APPROVED** [review]

**Review by chaitu236 — APPROVED** [review]

**Pull request merged**
