### PR TITLE
[RFC] Backport OpenSSL 1.1.1 to sumo

### PR DESCRIPTION
**Pull request by rtollert**
Now that RHEL 7 support is on its way out, _almost_ all supported Linux distributions support OpenSSL 1.1.1; the odd man out is ARM NILRT on sumo. Guaranteeing that OpenSSL 1.1.1 is present on all distributions greatly simplifies OpenSSL usage.

The following is an attempt at backporting all OpenSSL changes made through hardknott. A manual conflict was resolved at 1b822e36 and a change was inserted at 4d0fd928 to potentially allow openssl10 to be installed side-by-side. I forget what the deal is with libgpg-error.

I am unsuccessful so far in building stock sumo as of yet so all of this is untested.

### CODE REVIEW

**Comment by rtollert** [comment]
Feedback requested on
- Which tests I should run
- What builds should be confirmed to still work
- Etc.

**Comment by amstewart** [comment]
\<discussed offline>

**Comment by rtollert** [comment]
Update: we're probably upgrading to OpenSSL 3.0 instead. For maximum cherry-picking potential I'll probably just stack the 3.0 patches on top of these.

**Comment by rtollert** [comment]
I'm retracting this PR for now because
- we're not certain quite yet whether to move to 1.1 or 3.0
- I've cherry-picked a lot more stuff for the 1.1 version and I don't want people getting spammed

**Pull request closed without merging**
