### PR TITLE
sysvinit: Reapply bootlogd patch over sysvinit_2.96.

### PR DESCRIPTION
**Pull request by shruthi-ravi**
Built recipe. Overall image verification changes pending
@ni/rtos

### CODE REVIEW

**Review by bstreiff — COMMENTED** [review]
Commit title should be prefixed with the recipe name, like `sysvinit: Reapply bootlogd patch over sysvinit_2.96`.

**Review by amstewart — APPROVED** [review]
Looks good to me; ship it.

**Review by amstewart — COMMENTED** [review]
>Change pulled from upstream dunfell branch.

Was this change split from a larger commit which we do not want to pull, for some reason? I'd like to avoid more out-of-stream commits, if we can.

**Comment by shruthi-ravi** [comment]
I wish these newer commits hadn't piled on to this PR. Guess they did because the PR was still open? Are you fine with the way it is? I can create a new PR.

> Was this change split from a larger commit which we do not want to pull, for some reason?

No, this change wasn't split from a larger commit. This commit as it is is the only [difference](https://github.com/openembedded/openembedded-core/commits/dunfell/meta/recipes-support/iso-codes) between our branch and upstream dunfell.

**Comment by amstewart** [comment]
> I wish these newer commits hadn't piled on to this PR. Guess they did because the PR was still open? Are you fine with the way it is? I can create a new PR.

Ah; OK. Could you reset the PR ref back to the original commits and push the new commits to a different ref. Then I will pull just the sysvinit commit.

> No, this change wasn't split from a larger commit. This commit as it is is the only [difference](https://github.com/openembedded/openembedded-core/commits/dunfell/meta/recipes-support/iso-codes) between our branch and upstream dunfell.

In that case, could you replace it with a cherry-pick from upstream. The patch would drop out either way on the next rebase, but cherry-picking it will be more informative to the future maintainer.

**Comment by shruthi-ravi** [comment]
Fixed.

**Pull request merged**
